#!/usr/bin/env bash

function cmd_version {
    echo "tables 0.1.0"
}

function cmd_usage {
    cmd_version
    echo
    cat <<_EOF
Usage:
    tables [options] file

Options:
    $PROGRAM
        Show options for converting files to LaTeX tables.
    $PROGRAM help
        Show this text.
    $PROGRAM version
        Show version information.
_EOF
}

function cmd_main {
    NUMCOLS=$(head -n 1 $1 | awk -F "," '{ print NF }')
    ALIGN="$(printf "%0.s c" $(seq $NUMCOLS)) "

    printf "\\\begin{tabular}{$ALIGN}\n"
    printf "$(sed "s/,/ \& /g" $1 | sed "s/$/ \\\\\\\\\\\/g" | column -t) \n"
    printf "\\\end{tabular}\n"
}

PROGRAM="${0##*/}"

case "$1" in
    help|--help) shift;             cmd_usage "$@";;
    version|--version|-v) shift;    cmd_version "$@";;
    *)                              cmd_main "$@";;
esac
exit 0
